FROM ghcr.io/dockhippie/php-apache:8.4-amd64@sha256:8f1a87b2d4f1f705160af532ff5578c716b2d34580abe1411b5f6f9be8189d09

VOLUME ["/var/lib/kanboard"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php${PHP_PACKAGE_VERSION}-ldap sqlite git && \
  rm -rf /var/cache/apk/*

ENV PHP_COMPOSER_INSTALL=false

# renovate: datasource=github-releases depName=kanboard/kanboard
ENV KANBOARD_VERSION=1.2.47

# renovate: datasource=github-releases depName=aptible/supercronic
ENV SUPERCRONIC_VERSION=0.2.34

RUN curl -sSLo - https://github.com/kanboard/kanboard/archive/refs/tags/v${KANBOARD_VERSION}.tar.gz | tar -xzf - --strip 1 -C /srv/www && \
  cd /srv/www && \
  rm -rf .devcontainer custom-hooks data plugins web.config && \
  chown -R apache:apache /srv/www && \
  curl -sSLo /usr/bin/supercronic https://github.com/aptible/supercronic/releases/download/v${SUPERCRONIC_VERSION}/supercronic-linux-amd64 && \
  chmod +x /usr/bin/supercronic

COPY ./overlay /
