FROM ghcr.io/dockhippie/php-apache:8.4-arm@sha256:00952a56f34f106705a4877de8a28a01ad2601178eead2e1a091488be25c6b27

VOLUME ["/var/lib/kanboard"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php${PHP_PACKAGE_VERSION}-ldap sqlite git && \
  rm -rf /var/cache/apk/*

ENV PHP_COMPOSER_INSTALL=false

# renovate: datasource=github-releases depName=kanboard/kanboard
ENV KANBOARD_VERSION=1.2.49

# renovate: datasource=github-releases depName=aptible/supercronic
ENV SUPERCRONIC_VERSION=0.2.41

RUN curl -sSLo - https://github.com/kanboard/kanboard/archive/refs/tags/v${KANBOARD_VERSION}.tar.gz | tar -xzf - --strip 1 -C /srv/www && \
  cd /srv/www && \
  rm -rf .devcontainer custom-hooks data plugins web.config && \
  chown -R apache:apache /srv/www && \
  curl -sSLo /usr/bin/supercronic https://github.com/aptible/supercronic/releases/download/v${SUPERCRONIC_VERSION}/supercronic-linux-arm && \
  chmod +x /usr/bin/supercronic

COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/cli /usr/bin/container* && \
  chmod +x /usr/bin/cli /usr/bin/container* /etc/container.d/*.sh /etc/entrypoint.d/*.sh
