FROM ghcr.io/dockhippie/php-apache:8.4-amd64@sha256:81f94b2a5ad56478fa1d4cbdca1e4de33f51c5f6502c72117aae1ed21f69f12f

VOLUME ["/var/lib/kanboard"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php${PHP_PACKAGE_VERSION}-ldap sqlite git && \
  rm -rf /var/cache/apk/*

ENV PHP_COMPOSER_INSTALL=false

# renovate: datasource=github-releases depName=kanboard/kanboard
ENV KANBOARD_VERSION=1.1.1

# renovate: datasource=github-releases depName=aptible/supercronic
ENV SUPERCRONIC_VERSION=0.2.39

RUN curl -sSLo - https://github.com/kanboard/kanboard/archive/refs/tags/v${KANBOARD_VERSION}.tar.gz | tar -xzf - --strip 1 -C /srv/www && \
  cd /srv/www && \
  rm -rf .devcontainer custom-hooks data plugins web.config && \
  chown -R apache:apache /srv/www && \
  curl -sSLo /usr/bin/supercronic https://github.com/aptible/supercronic/releases/download/v${SUPERCRONIC_VERSION}/supercronic-linux-amd64 && \
  chmod +x /usr/bin/supercronic

COPY ./overlay /
